package com.stock.dao.model.sys;

import java.io.Serializable;
import java.util.Date;

public class SysAttachment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.attachment_id
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    private Integer attachmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.business_table
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    private String businessTable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.business_id
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.attachment_name
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    private String attachmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.attachment_path
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    private String attachmentPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.title
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.type
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.description
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.creator
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.create_time
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.access_group
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    private Integer accessGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.amender
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    private Integer amender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.amend_time
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    private Date amendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.record_version
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    private Integer recordVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_attachment.is_deleted
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_attachment
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.attachment_id
     *
     * @return the value of sys_attachment.attachment_id
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public Integer getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.attachment_id
     *
     * @param attachmentId the value for sys_attachment.attachment_id
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public void setAttachmentId(Integer attachmentId) {
        this.attachmentId = attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.business_table
     *
     * @return the value of sys_attachment.business_table
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public String getBusinessTable() {
        return businessTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.business_table
     *
     * @param businessTable the value for sys_attachment.business_table
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public void setBusinessTable(String businessTable) {
        this.businessTable = businessTable == null ? null : businessTable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.business_id
     *
     * @return the value of sys_attachment.business_id
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.business_id
     *
     * @param businessId the value for sys_attachment.business_id
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.attachment_name
     *
     * @return the value of sys_attachment.attachment_name
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public String getAttachmentName() {
        return attachmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.attachment_name
     *
     * @param attachmentName the value for sys_attachment.attachment_name
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public void setAttachmentName(String attachmentName) {
        this.attachmentName = attachmentName == null ? null : attachmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.attachment_path
     *
     * @return the value of sys_attachment.attachment_path
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public String getAttachmentPath() {
        return attachmentPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.attachment_path
     *
     * @param attachmentPath the value for sys_attachment.attachment_path
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public void setAttachmentPath(String attachmentPath) {
        this.attachmentPath = attachmentPath == null ? null : attachmentPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.title
     *
     * @return the value of sys_attachment.title
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.title
     *
     * @param title the value for sys_attachment.title
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.type
     *
     * @return the value of sys_attachment.type
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.type
     *
     * @param type the value for sys_attachment.type
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.description
     *
     * @return the value of sys_attachment.description
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.description
     *
     * @param description the value for sys_attachment.description
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.creator
     *
     * @return the value of sys_attachment.creator
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.creator
     *
     * @param creator the value for sys_attachment.creator
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.create_time
     *
     * @return the value of sys_attachment.create_time
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.create_time
     *
     * @param createTime the value for sys_attachment.create_time
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.access_group
     *
     * @return the value of sys_attachment.access_group
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public Integer getAccessGroup() {
        return accessGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.access_group
     *
     * @param accessGroup the value for sys_attachment.access_group
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public void setAccessGroup(Integer accessGroup) {
        this.accessGroup = accessGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.amender
     *
     * @return the value of sys_attachment.amender
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public Integer getAmender() {
        return amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.amender
     *
     * @param amender the value for sys_attachment.amender
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public void setAmender(Integer amender) {
        this.amender = amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.amend_time
     *
     * @return the value of sys_attachment.amend_time
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public Date getAmendTime() {
        return amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.amend_time
     *
     * @param amendTime the value for sys_attachment.amend_time
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public void setAmendTime(Date amendTime) {
        this.amendTime = amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.record_version
     *
     * @return the value of sys_attachment.record_version
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public Integer getRecordVersion() {
        return recordVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.record_version
     *
     * @param recordVersion the value for sys_attachment.record_version
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public void setRecordVersion(Integer recordVersion) {
        this.recordVersion = recordVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_attachment.is_deleted
     *
     * @return the value of sys_attachment.is_deleted
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_attachment.is_deleted
     *
     * @param isDeleted the value for sys_attachment.is_deleted
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysAttachment other = (SysAttachment) that;
        return (this.getAttachmentId() == null ? other.getAttachmentId() == null : this.getAttachmentId().equals(other.getAttachmentId()))
            && (this.getBusinessTable() == null ? other.getBusinessTable() == null : this.getBusinessTable().equals(other.getBusinessTable()))
            && (this.getBusinessId() == null ? other.getBusinessId() == null : this.getBusinessId().equals(other.getBusinessId()))
            && (this.getAttachmentName() == null ? other.getAttachmentName() == null : this.getAttachmentName().equals(other.getAttachmentName()))
            && (this.getAttachmentPath() == null ? other.getAttachmentPath() == null : this.getAttachmentPath().equals(other.getAttachmentPath()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getAccessGroup() == null ? other.getAccessGroup() == null : this.getAccessGroup().equals(other.getAccessGroup()))
            && (this.getAmender() == null ? other.getAmender() == null : this.getAmender().equals(other.getAmender()))
            && (this.getAmendTime() == null ? other.getAmendTime() == null : this.getAmendTime().equals(other.getAmendTime()))
            && (this.getRecordVersion() == null ? other.getRecordVersion() == null : this.getRecordVersion().equals(other.getRecordVersion()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAttachmentId() == null) ? 0 : getAttachmentId().hashCode());
        result = prime * result + ((getBusinessTable() == null) ? 0 : getBusinessTable().hashCode());
        result = prime * result + ((getBusinessId() == null) ? 0 : getBusinessId().hashCode());
        result = prime * result + ((getAttachmentName() == null) ? 0 : getAttachmentName().hashCode());
        result = prime * result + ((getAttachmentPath() == null) ? 0 : getAttachmentPath().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getAccessGroup() == null) ? 0 : getAccessGroup().hashCode());
        result = prime * result + ((getAmender() == null) ? 0 : getAmender().hashCode());
        result = prime * result + ((getAmendTime() == null) ? 0 : getAmendTime().hashCode());
        result = prime * result + ((getRecordVersion() == null) ? 0 : getRecordVersion().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_attachment
     *
     * @mbggenerated Tue Jun 27 15:46:09 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", attachmentId=").append(attachmentId);
        sb.append(", businessTable=").append(businessTable);
        sb.append(", businessId=").append(businessId);
        sb.append(", attachmentName=").append(attachmentName);
        sb.append(", attachmentPath=").append(attachmentPath);
        sb.append(", title=").append(title);
        sb.append(", type=").append(type);
        sb.append(", description=").append(description);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", accessGroup=").append(accessGroup);
        sb.append(", amender=").append(amender);
        sb.append(", amendTime=").append(amendTime);
        sb.append(", recordVersion=").append(recordVersion);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}