package com.stock.dao.mapper.sys;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.stock.dao.model.sys.SysAuthentication;
import com.stock.dao.model.sys.SysAuthenticationExample;

public interface SysAuthenticationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authentication
     *
     * @mbggenerated Mon May 22 06:22:45 CST 2017
     */
    int countByExample(SysAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authentication
     *
     * @mbggenerated Mon May 22 06:22:45 CST 2017
     */
    int deleteByExample(SysAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authentication
     *
     * @mbggenerated Mon May 22 06:22:45 CST 2017
     */
    int deleteByPrimaryKey(Integer authenticationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authentication
     *
     * @mbggenerated Mon May 22 06:22:45 CST 2017
     */
    int insert(SysAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authentication
     *
     * @mbggenerated Mon May 22 06:22:45 CST 2017
     */
    int insertSelective(SysAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authentication
     *
     * @mbggenerated Mon May 22 06:22:45 CST 2017
     */
    List<SysAuthentication> selectByExample(SysAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authentication
     *
     * @mbggenerated Mon May 22 06:22:45 CST 2017
     */
    SysAuthentication selectByPrimaryKey(Integer authenticationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authentication
     *
     * @mbggenerated Mon May 22 06:22:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysAuthentication record, @Param("example") SysAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authentication
     *
     * @mbggenerated Mon May 22 06:22:45 CST 2017
     */
    int updateByExample(@Param("record") SysAuthentication record, @Param("example") SysAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authentication
     *
     * @mbggenerated Mon May 22 06:22:45 CST 2017
     */
    int updateByPrimaryKeySelective(SysAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authentication
     *
     * @mbggenerated Mon May 22 06:22:45 CST 2017
     */
    int updateByPrimaryKey(SysAuthentication record);
}