package com.stock.dao.mapper.sys;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.stock.dao.model.sys.SysCustomer;
import com.stock.dao.model.sys.SysCustomerExample;

public interface SysCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_customer
     *
     * @mbggenerated Fri Feb 02 16:06:03 CST 2018
     */
    int countByExample(SysCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_customer
     *
     * @mbggenerated Fri Feb 02 16:06:03 CST 2018
     */
    int deleteByExample(SysCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_customer
     *
     * @mbggenerated Fri Feb 02 16:06:03 CST 2018
     */
    int deleteByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_customer
     *
     * @mbggenerated Fri Feb 02 16:06:03 CST 2018
     */
    int insert(SysCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_customer
     *
     * @mbggenerated Fri Feb 02 16:06:03 CST 2018
     */
    int insertSelective(SysCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_customer
     *
     * @mbggenerated Fri Feb 02 16:06:03 CST 2018
     */
    List<SysCustomer> selectByExample(SysCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_customer
     *
     * @mbggenerated Fri Feb 02 16:06:03 CST 2018
     */
    SysCustomer selectByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_customer
     *
     * @mbggenerated Fri Feb 02 16:06:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysCustomer record, @Param("example") SysCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_customer
     *
     * @mbggenerated Fri Feb 02 16:06:03 CST 2018
     */
    int updateByExample(@Param("record") SysCustomer record, @Param("example") SysCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_customer
     *
     * @mbggenerated Fri Feb 02 16:06:03 CST 2018
     */
    int updateByPrimaryKeySelective(SysCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_customer
     *
     * @mbggenerated Fri Feb 02 16:06:03 CST 2018
     */
    int updateByPrimaryKey(SysCustomer record);
}