package com.stock.dao.mapper.stock;

import com.stock.dao.model.stock.BuyerHistoryEntrustRecord;
import com.stock.dao.model.stock.BuyerHistoryEntrustRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuyerHistoryEntrustRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_history_entrust_record
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    int countByExample(BuyerHistoryEntrustRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_history_entrust_record
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    int deleteByExample(BuyerHistoryEntrustRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_history_entrust_record
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    int deleteByPrimaryKey(Integer buyerHistoryEntrustRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_history_entrust_record
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    int insert(BuyerHistoryEntrustRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_history_entrust_record
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    int insertSelective(BuyerHistoryEntrustRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_history_entrust_record
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    List<BuyerHistoryEntrustRecord> selectByExample(BuyerHistoryEntrustRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_history_entrust_record
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    BuyerHistoryEntrustRecord selectByPrimaryKey(Integer buyerHistoryEntrustRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_history_entrust_record
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") BuyerHistoryEntrustRecord record, @Param("example") BuyerHistoryEntrustRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_history_entrust_record
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    int updateByExample(@Param("record") BuyerHistoryEntrustRecord record, @Param("example") BuyerHistoryEntrustRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_history_entrust_record
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    int updateByPrimaryKeySelective(BuyerHistoryEntrustRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_history_entrust_record
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    int updateByPrimaryKey(BuyerHistoryEntrustRecord record);
}