package com.stock.dao.mapper.stock;

import com.stock.dao.model.stock.BuyerSellerHistoryEntrustRecord;
import com.stock.dao.model.stock.BuyerSellerHistoryEntrustRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuyerSellerHistoryEntrustRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int countByExample(BuyerSellerHistoryEntrustRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int deleteByExample(BuyerSellerHistoryEntrustRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int deleteByPrimaryKey(Integer buyerSellerHistoryEntrustRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int insert(BuyerSellerHistoryEntrustRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int insertSelective(BuyerSellerHistoryEntrustRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    List<BuyerSellerHistoryEntrustRecord> selectByExample(BuyerSellerHistoryEntrustRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    BuyerSellerHistoryEntrustRecord selectByPrimaryKey(Integer buyerSellerHistoryEntrustRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") BuyerSellerHistoryEntrustRecord record, @Param("example") BuyerSellerHistoryEntrustRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int updateByExample(@Param("record") BuyerSellerHistoryEntrustRecord record, @Param("example") BuyerSellerHistoryEntrustRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int updateByPrimaryKeySelective(BuyerSellerHistoryEntrustRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int updateByPrimaryKey(BuyerSellerHistoryEntrustRecord record);
}