package com.stock.dao.mapper.stock;

import com.stock.dao.model.stock.SellerEntrustPriceQueue;
import com.stock.dao.model.stock.SellerEntrustPriceQueueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SellerEntrustPriceQueueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_entrust_price_queue
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int countByExample(SellerEntrustPriceQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_entrust_price_queue
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int deleteByExample(SellerEntrustPriceQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_entrust_price_queue
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int deleteByPrimaryKey(Integer sellerEntrustPriceQueueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_entrust_price_queue
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int insert(SellerEntrustPriceQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_entrust_price_queue
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int insertSelective(SellerEntrustPriceQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_entrust_price_queue
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    List<SellerEntrustPriceQueue> selectByExample(SellerEntrustPriceQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_entrust_price_queue
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    SellerEntrustPriceQueue selectByPrimaryKey(Integer sellerEntrustPriceQueueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_entrust_price_queue
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") SellerEntrustPriceQueue record, @Param("example") SellerEntrustPriceQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_entrust_price_queue
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int updateByExample(@Param("record") SellerEntrustPriceQueue record, @Param("example") SellerEntrustPriceQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_entrust_price_queue
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int updateByPrimaryKeySelective(SellerEntrustPriceQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_entrust_price_queue
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    int updateByPrimaryKey(SellerEntrustPriceQueue record);
}