package com.stock.dao.model.stock;

import java.io.Serializable;
import java.util.Date;

public class BuyerEntrustPriceQueue implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_entrust_price_queue.buyer_entrust_price_queue_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer buyerEntrustPriceQueueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_entrust_price_queue.buyer_entrust_price_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer buyerEntrustPriceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_entrust_price_queue.user_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_entrust_price_queue.entrust_date
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Date entrustDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_entrust_price_queue.entrust_num
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer entrustNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_entrust_price_queue.creator
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_entrust_price_queue.create_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_entrust_price_queue.amender
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer amender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_entrust_price_queue.amend_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Date amendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer_entrust_price_queue.access_group
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer accessGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buyer_entrust_price_queue
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_entrust_price_queue.buyer_entrust_price_queue_id
     *
     * @return the value of buyer_entrust_price_queue.buyer_entrust_price_queue_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getBuyerEntrustPriceQueueId() {
        return buyerEntrustPriceQueueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_entrust_price_queue.buyer_entrust_price_queue_id
     *
     * @param buyerEntrustPriceQueueId the value for buyer_entrust_price_queue.buyer_entrust_price_queue_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setBuyerEntrustPriceQueueId(Integer buyerEntrustPriceQueueId) {
        this.buyerEntrustPriceQueueId = buyerEntrustPriceQueueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_entrust_price_queue.buyer_entrust_price_id
     *
     * @return the value of buyer_entrust_price_queue.buyer_entrust_price_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getBuyerEntrustPriceId() {
        return buyerEntrustPriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_entrust_price_queue.buyer_entrust_price_id
     *
     * @param buyerEntrustPriceId the value for buyer_entrust_price_queue.buyer_entrust_price_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setBuyerEntrustPriceId(Integer buyerEntrustPriceId) {
        this.buyerEntrustPriceId = buyerEntrustPriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_entrust_price_queue.user_id
     *
     * @return the value of buyer_entrust_price_queue.user_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_entrust_price_queue.user_id
     *
     * @param userId the value for buyer_entrust_price_queue.user_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_entrust_price_queue.entrust_date
     *
     * @return the value of buyer_entrust_price_queue.entrust_date
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Date getEntrustDate() {
        return entrustDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_entrust_price_queue.entrust_date
     *
     * @param entrustDate the value for buyer_entrust_price_queue.entrust_date
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setEntrustDate(Date entrustDate) {
        this.entrustDate = entrustDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_entrust_price_queue.entrust_num
     *
     * @return the value of buyer_entrust_price_queue.entrust_num
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getEntrustNum() {
        return entrustNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_entrust_price_queue.entrust_num
     *
     * @param entrustNum the value for buyer_entrust_price_queue.entrust_num
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setEntrustNum(Integer entrustNum) {
        this.entrustNum = entrustNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_entrust_price_queue.creator
     *
     * @return the value of buyer_entrust_price_queue.creator
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_entrust_price_queue.creator
     *
     * @param creator the value for buyer_entrust_price_queue.creator
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_entrust_price_queue.create_time
     *
     * @return the value of buyer_entrust_price_queue.create_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_entrust_price_queue.create_time
     *
     * @param createTime the value for buyer_entrust_price_queue.create_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_entrust_price_queue.amender
     *
     * @return the value of buyer_entrust_price_queue.amender
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getAmender() {
        return amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_entrust_price_queue.amender
     *
     * @param amender the value for buyer_entrust_price_queue.amender
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setAmender(Integer amender) {
        this.amender = amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_entrust_price_queue.amend_time
     *
     * @return the value of buyer_entrust_price_queue.amend_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Date getAmendTime() {
        return amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_entrust_price_queue.amend_time
     *
     * @param amendTime the value for buyer_entrust_price_queue.amend_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setAmendTime(Date amendTime) {
        this.amendTime = amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer_entrust_price_queue.access_group
     *
     * @return the value of buyer_entrust_price_queue.access_group
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getAccessGroup() {
        return accessGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer_entrust_price_queue.access_group
     *
     * @param accessGroup the value for buyer_entrust_price_queue.access_group
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setAccessGroup(Integer accessGroup) {
        this.accessGroup = accessGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_entrust_price_queue
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BuyerEntrustPriceQueue other = (BuyerEntrustPriceQueue) that;
        return (this.getBuyerEntrustPriceQueueId() == null ? other.getBuyerEntrustPriceQueueId() == null : this.getBuyerEntrustPriceQueueId().equals(other.getBuyerEntrustPriceQueueId()))
            && (this.getBuyerEntrustPriceId() == null ? other.getBuyerEntrustPriceId() == null : this.getBuyerEntrustPriceId().equals(other.getBuyerEntrustPriceId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getEntrustDate() == null ? other.getEntrustDate() == null : this.getEntrustDate().equals(other.getEntrustDate()))
            && (this.getEntrustNum() == null ? other.getEntrustNum() == null : this.getEntrustNum().equals(other.getEntrustNum()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getAmender() == null ? other.getAmender() == null : this.getAmender().equals(other.getAmender()))
            && (this.getAmendTime() == null ? other.getAmendTime() == null : this.getAmendTime().equals(other.getAmendTime()))
            && (this.getAccessGroup() == null ? other.getAccessGroup() == null : this.getAccessGroup().equals(other.getAccessGroup()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_entrust_price_queue
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBuyerEntrustPriceQueueId() == null) ? 0 : getBuyerEntrustPriceQueueId().hashCode());
        result = prime * result + ((getBuyerEntrustPriceId() == null) ? 0 : getBuyerEntrustPriceId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getEntrustDate() == null) ? 0 : getEntrustDate().hashCode());
        result = prime * result + ((getEntrustNum() == null) ? 0 : getEntrustNum().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getAmender() == null) ? 0 : getAmender().hashCode());
        result = prime * result + ((getAmendTime() == null) ? 0 : getAmendTime().hashCode());
        result = prime * result + ((getAccessGroup() == null) ? 0 : getAccessGroup().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_entrust_price_queue
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", buyerEntrustPriceQueueId=").append(buyerEntrustPriceQueueId);
        sb.append(", buyerEntrustPriceId=").append(buyerEntrustPriceId);
        sb.append(", userId=").append(userId);
        sb.append(", entrustDate=").append(entrustDate);
        sb.append(", entrustNum=").append(entrustNum);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", amender=").append(amender);
        sb.append(", amendTime=").append(amendTime);
        sb.append(", accessGroup=").append(accessGroup);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}