package com.stock.dao.model.stock;

import com.stock.dao.page.Page;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BuyerSellerHistoryEntrustRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public BuyerSellerHistoryEntrustRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBuyerSellerHistoryEntrustRecordIdIsNull() {
            addCriterion("buyer_seller_history_entrust_record_id is null");
            return (Criteria) this;
        }

        public Criteria andBuyerSellerHistoryEntrustRecordIdIsNotNull() {
            addCriterion("buyer_seller_history_entrust_record_id is not null");
            return (Criteria) this;
        }

        public Criteria andBuyerSellerHistoryEntrustRecordIdEqualTo(Integer value) {
            addCriterion("buyer_seller_history_entrust_record_id =", value, "buyerSellerHistoryEntrustRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyerSellerHistoryEntrustRecordIdNotEqualTo(Integer value) {
            addCriterion("buyer_seller_history_entrust_record_id <>", value, "buyerSellerHistoryEntrustRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyerSellerHistoryEntrustRecordIdGreaterThan(Integer value) {
            addCriterion("buyer_seller_history_entrust_record_id >", value, "buyerSellerHistoryEntrustRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyerSellerHistoryEntrustRecordIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("buyer_seller_history_entrust_record_id >=", value, "buyerSellerHistoryEntrustRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyerSellerHistoryEntrustRecordIdLessThan(Integer value) {
            addCriterion("buyer_seller_history_entrust_record_id <", value, "buyerSellerHistoryEntrustRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyerSellerHistoryEntrustRecordIdLessThanOrEqualTo(Integer value) {
            addCriterion("buyer_seller_history_entrust_record_id <=", value, "buyerSellerHistoryEntrustRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyerSellerHistoryEntrustRecordIdIn(List<Integer> values) {
            addCriterion("buyer_seller_history_entrust_record_id in", values, "buyerSellerHistoryEntrustRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyerSellerHistoryEntrustRecordIdNotIn(List<Integer> values) {
            addCriterion("buyer_seller_history_entrust_record_id not in", values, "buyerSellerHistoryEntrustRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyerSellerHistoryEntrustRecordIdBetween(Integer value1, Integer value2) {
            addCriterion("buyer_seller_history_entrust_record_id between", value1, value2, "buyerSellerHistoryEntrustRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyerSellerHistoryEntrustRecordIdNotBetween(Integer value1, Integer value2) {
            addCriterion("buyer_seller_history_entrust_record_id not between", value1, value2, "buyerSellerHistoryEntrustRecordId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdIsNull() {
            addCriterion("buyer_id is null");
            return (Criteria) this;
        }

        public Criteria andBuyerIdIsNotNull() {
            addCriterion("buyer_id is not null");
            return (Criteria) this;
        }

        public Criteria andBuyerIdEqualTo(Integer value) {
            addCriterion("buyer_id =", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdNotEqualTo(Integer value) {
            addCriterion("buyer_id <>", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdGreaterThan(Integer value) {
            addCriterion("buyer_id >", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("buyer_id >=", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdLessThan(Integer value) {
            addCriterion("buyer_id <", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdLessThanOrEqualTo(Integer value) {
            addCriterion("buyer_id <=", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdIn(List<Integer> values) {
            addCriterion("buyer_id in", values, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdNotIn(List<Integer> values) {
            addCriterion("buyer_id not in", values, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdBetween(Integer value1, Integer value2) {
            addCriterion("buyer_id between", value1, value2, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("buyer_id not between", value1, value2, "buyerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdIsNull() {
            addCriterion("seller_id is null");
            return (Criteria) this;
        }

        public Criteria andSellerIdIsNotNull() {
            addCriterion("seller_id is not null");
            return (Criteria) this;
        }

        public Criteria andSellerIdEqualTo(Integer value) {
            addCriterion("seller_id =", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotEqualTo(Integer value) {
            addCriterion("seller_id <>", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdGreaterThan(Integer value) {
            addCriterion("seller_id >", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("seller_id >=", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLessThan(Integer value) {
            addCriterion("seller_id <", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLessThanOrEqualTo(Integer value) {
            addCriterion("seller_id <=", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdIn(List<Integer> values) {
            addCriterion("seller_id in", values, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotIn(List<Integer> values) {
            addCriterion("seller_id not in", values, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdBetween(Integer value1, Integer value2) {
            addCriterion("seller_id between", value1, value2, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("seller_id not between", value1, value2, "sellerId");
            return (Criteria) this;
        }

        public Criteria andDealPriceIsNull() {
            addCriterion("deal_price is null");
            return (Criteria) this;
        }

        public Criteria andDealPriceIsNotNull() {
            addCriterion("deal_price is not null");
            return (Criteria) this;
        }

        public Criteria andDealPriceEqualTo(Double value) {
            addCriterion("deal_price =", value, "dealPrice");
            return (Criteria) this;
        }

        public Criteria andDealPriceNotEqualTo(Double value) {
            addCriterion("deal_price <>", value, "dealPrice");
            return (Criteria) this;
        }

        public Criteria andDealPriceGreaterThan(Double value) {
            addCriterion("deal_price >", value, "dealPrice");
            return (Criteria) this;
        }

        public Criteria andDealPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("deal_price >=", value, "dealPrice");
            return (Criteria) this;
        }

        public Criteria andDealPriceLessThan(Double value) {
            addCriterion("deal_price <", value, "dealPrice");
            return (Criteria) this;
        }

        public Criteria andDealPriceLessThanOrEqualTo(Double value) {
            addCriterion("deal_price <=", value, "dealPrice");
            return (Criteria) this;
        }

        public Criteria andDealPriceIn(List<Double> values) {
            addCriterion("deal_price in", values, "dealPrice");
            return (Criteria) this;
        }

        public Criteria andDealPriceNotIn(List<Double> values) {
            addCriterion("deal_price not in", values, "dealPrice");
            return (Criteria) this;
        }

        public Criteria andDealPriceBetween(Double value1, Double value2) {
            addCriterion("deal_price between", value1, value2, "dealPrice");
            return (Criteria) this;
        }

        public Criteria andDealPriceNotBetween(Double value1, Double value2) {
            addCriterion("deal_price not between", value1, value2, "dealPrice");
            return (Criteria) this;
        }

        public Criteria andDealNumIsNull() {
            addCriterion("deal_num is null");
            return (Criteria) this;
        }

        public Criteria andDealNumIsNotNull() {
            addCriterion("deal_num is not null");
            return (Criteria) this;
        }

        public Criteria andDealNumEqualTo(Integer value) {
            addCriterion("deal_num =", value, "dealNum");
            return (Criteria) this;
        }

        public Criteria andDealNumNotEqualTo(Integer value) {
            addCriterion("deal_num <>", value, "dealNum");
            return (Criteria) this;
        }

        public Criteria andDealNumGreaterThan(Integer value) {
            addCriterion("deal_num >", value, "dealNum");
            return (Criteria) this;
        }

        public Criteria andDealNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("deal_num >=", value, "dealNum");
            return (Criteria) this;
        }

        public Criteria andDealNumLessThan(Integer value) {
            addCriterion("deal_num <", value, "dealNum");
            return (Criteria) this;
        }

        public Criteria andDealNumLessThanOrEqualTo(Integer value) {
            addCriterion("deal_num <=", value, "dealNum");
            return (Criteria) this;
        }

        public Criteria andDealNumIn(List<Integer> values) {
            addCriterion("deal_num in", values, "dealNum");
            return (Criteria) this;
        }

        public Criteria andDealNumNotIn(List<Integer> values) {
            addCriterion("deal_num not in", values, "dealNum");
            return (Criteria) this;
        }

        public Criteria andDealNumBetween(Integer value1, Integer value2) {
            addCriterion("deal_num between", value1, value2, "dealNum");
            return (Criteria) this;
        }

        public Criteria andDealNumNotBetween(Integer value1, Integer value2) {
            addCriterion("deal_num not between", value1, value2, "dealNum");
            return (Criteria) this;
        }

        public Criteria andDealDateIsNull() {
            addCriterion("deal_date is null");
            return (Criteria) this;
        }

        public Criteria andDealDateIsNotNull() {
            addCriterion("deal_date is not null");
            return (Criteria) this;
        }

        public Criteria andDealDateEqualTo(Date value) {
            addCriterion("deal_date =", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateNotEqualTo(Date value) {
            addCriterion("deal_date <>", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateGreaterThan(Date value) {
            addCriterion("deal_date >", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateGreaterThanOrEqualTo(Date value) {
            addCriterion("deal_date >=", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateLessThan(Date value) {
            addCriterion("deal_date <", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateLessThanOrEqualTo(Date value) {
            addCriterion("deal_date <=", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateIn(List<Date> values) {
            addCriterion("deal_date in", values, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateNotIn(List<Date> values) {
            addCriterion("deal_date not in", values, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateBetween(Date value1, Date value2) {
            addCriterion("deal_date between", value1, value2, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateNotBetween(Date value1, Date value2) {
            addCriterion("deal_date not between", value1, value2, "dealDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 01 14:24:56 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buyer_seller_history_entrust_record
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}