package com.stock.dao.model.stock;

import java.io.Serializable;
import java.util.Date;

public class StockAccount implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_account.stock_account_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer stockAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_account.total_asset
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Double totalAsset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_account.stock_asset
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Double stockAsset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_account.remaining_fund
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Double remainingFund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_account.advisable_fund
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Double advisableFund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_account.available_fund
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Double availableFund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_account.freeze_fund
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Double freezeFund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_account.user_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_account.creator
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_account.create_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_account.amender
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer amender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_account.amend_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Date amendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_account.access_group
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer accessGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_account
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_account.stock_account_id
     *
     * @return the value of stock_account.stock_account_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getStockAccountId() {
        return stockAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_account.stock_account_id
     *
     * @param stockAccountId the value for stock_account.stock_account_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setStockAccountId(Integer stockAccountId) {
        this.stockAccountId = stockAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_account.total_asset
     *
     * @return the value of stock_account.total_asset
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Double getTotalAsset() {
        return totalAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_account.total_asset
     *
     * @param totalAsset the value for stock_account.total_asset
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setTotalAsset(Double totalAsset) {
        this.totalAsset = totalAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_account.stock_asset
     *
     * @return the value of stock_account.stock_asset
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Double getStockAsset() {
        return stockAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_account.stock_asset
     *
     * @param stockAsset the value for stock_account.stock_asset
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setStockAsset(Double stockAsset) {
        this.stockAsset = stockAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_account.remaining_fund
     *
     * @return the value of stock_account.remaining_fund
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Double getRemainingFund() {
        return remainingFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_account.remaining_fund
     *
     * @param remainingFund the value for stock_account.remaining_fund
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setRemainingFund(Double remainingFund) {
        this.remainingFund = remainingFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_account.advisable_fund
     *
     * @return the value of stock_account.advisable_fund
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Double getAdvisableFund() {
        return advisableFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_account.advisable_fund
     *
     * @param advisableFund the value for stock_account.advisable_fund
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setAdvisableFund(Double advisableFund) {
        this.advisableFund = advisableFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_account.available_fund
     *
     * @return the value of stock_account.available_fund
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Double getAvailableFund() {
        return availableFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_account.available_fund
     *
     * @param availableFund the value for stock_account.available_fund
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setAvailableFund(Double availableFund) {
        this.availableFund = availableFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_account.freeze_fund
     *
     * @return the value of stock_account.freeze_fund
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Double getFreezeFund() {
        return freezeFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_account.freeze_fund
     *
     * @param freezeFund the value for stock_account.freeze_fund
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setFreezeFund(Double freezeFund) {
        this.freezeFund = freezeFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_account.user_id
     *
     * @return the value of stock_account.user_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_account.user_id
     *
     * @param userId the value for stock_account.user_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_account.creator
     *
     * @return the value of stock_account.creator
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_account.creator
     *
     * @param creator the value for stock_account.creator
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_account.create_time
     *
     * @return the value of stock_account.create_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_account.create_time
     *
     * @param createTime the value for stock_account.create_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_account.amender
     *
     * @return the value of stock_account.amender
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getAmender() {
        return amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_account.amender
     *
     * @param amender the value for stock_account.amender
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setAmender(Integer amender) {
        this.amender = amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_account.amend_time
     *
     * @return the value of stock_account.amend_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Date getAmendTime() {
        return amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_account.amend_time
     *
     * @param amendTime the value for stock_account.amend_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setAmendTime(Date amendTime) {
        this.amendTime = amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_account.access_group
     *
     * @return the value of stock_account.access_group
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getAccessGroup() {
        return accessGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_account.access_group
     *
     * @param accessGroup the value for stock_account.access_group
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setAccessGroup(Integer accessGroup) {
        this.accessGroup = accessGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_account
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StockAccount other = (StockAccount) that;
        return (this.getStockAccountId() == null ? other.getStockAccountId() == null : this.getStockAccountId().equals(other.getStockAccountId()))
            && (this.getTotalAsset() == null ? other.getTotalAsset() == null : this.getTotalAsset().equals(other.getTotalAsset()))
            && (this.getStockAsset() == null ? other.getStockAsset() == null : this.getStockAsset().equals(other.getStockAsset()))
            && (this.getRemainingFund() == null ? other.getRemainingFund() == null : this.getRemainingFund().equals(other.getRemainingFund()))
            && (this.getAdvisableFund() == null ? other.getAdvisableFund() == null : this.getAdvisableFund().equals(other.getAdvisableFund()))
            && (this.getAvailableFund() == null ? other.getAvailableFund() == null : this.getAvailableFund().equals(other.getAvailableFund()))
            && (this.getFreezeFund() == null ? other.getFreezeFund() == null : this.getFreezeFund().equals(other.getFreezeFund()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getAmender() == null ? other.getAmender() == null : this.getAmender().equals(other.getAmender()))
            && (this.getAmendTime() == null ? other.getAmendTime() == null : this.getAmendTime().equals(other.getAmendTime()))
            && (this.getAccessGroup() == null ? other.getAccessGroup() == null : this.getAccessGroup().equals(other.getAccessGroup()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_account
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStockAccountId() == null) ? 0 : getStockAccountId().hashCode());
        result = prime * result + ((getTotalAsset() == null) ? 0 : getTotalAsset().hashCode());
        result = prime * result + ((getStockAsset() == null) ? 0 : getStockAsset().hashCode());
        result = prime * result + ((getRemainingFund() == null) ? 0 : getRemainingFund().hashCode());
        result = prime * result + ((getAdvisableFund() == null) ? 0 : getAdvisableFund().hashCode());
        result = prime * result + ((getAvailableFund() == null) ? 0 : getAvailableFund().hashCode());
        result = prime * result + ((getFreezeFund() == null) ? 0 : getFreezeFund().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getAmender() == null) ? 0 : getAmender().hashCode());
        result = prime * result + ((getAmendTime() == null) ? 0 : getAmendTime().hashCode());
        result = prime * result + ((getAccessGroup() == null) ? 0 : getAccessGroup().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_account
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", stockAccountId=").append(stockAccountId);
        sb.append(", totalAsset=").append(totalAsset);
        sb.append(", stockAsset=").append(stockAsset);
        sb.append(", remainingFund=").append(remainingFund);
        sb.append(", advisableFund=").append(advisableFund);
        sb.append(", availableFund=").append(availableFund);
        sb.append(", freezeFund=").append(freezeFund);
        sb.append(", userId=").append(userId);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", amender=").append(amender);
        sb.append(", amendTime=").append(amendTime);
        sb.append(", accessGroup=").append(accessGroup);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}