package com.stock.dao.model.stock;

import java.io.Serializable;
import java.util.Date;

public class StockTurnoverRate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_turnover_rate.stock_ternover_rate_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer stockTernoverRateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_turnover_rate.stock_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_turnover_rate.turnover_rate
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Double turnoverRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_turnover_rate.turnover_date
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Date turnoverDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_turnover_rate.creator
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_turnover_rate.create_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_turnover_rate.amender
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer amender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_turnover_rate.amend_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Date amendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_turnover_rate.access_group
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer accessGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_turnover_rate
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_turnover_rate.stock_ternover_rate_id
     *
     * @return the value of stock_turnover_rate.stock_ternover_rate_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getStockTernoverRateId() {
        return stockTernoverRateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_turnover_rate.stock_ternover_rate_id
     *
     * @param stockTernoverRateId the value for stock_turnover_rate.stock_ternover_rate_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setStockTernoverRateId(Integer stockTernoverRateId) {
        this.stockTernoverRateId = stockTernoverRateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_turnover_rate.stock_id
     *
     * @return the value of stock_turnover_rate.stock_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_turnover_rate.stock_id
     *
     * @param stockId the value for stock_turnover_rate.stock_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_turnover_rate.turnover_rate
     *
     * @return the value of stock_turnover_rate.turnover_rate
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Double getTurnoverRate() {
        return turnoverRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_turnover_rate.turnover_rate
     *
     * @param turnoverRate the value for stock_turnover_rate.turnover_rate
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setTurnoverRate(Double turnoverRate) {
        this.turnoverRate = turnoverRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_turnover_rate.turnover_date
     *
     * @return the value of stock_turnover_rate.turnover_date
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Date getTurnoverDate() {
        return turnoverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_turnover_rate.turnover_date
     *
     * @param turnoverDate the value for stock_turnover_rate.turnover_date
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setTurnoverDate(Date turnoverDate) {
        this.turnoverDate = turnoverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_turnover_rate.creator
     *
     * @return the value of stock_turnover_rate.creator
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_turnover_rate.creator
     *
     * @param creator the value for stock_turnover_rate.creator
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_turnover_rate.create_time
     *
     * @return the value of stock_turnover_rate.create_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_turnover_rate.create_time
     *
     * @param createTime the value for stock_turnover_rate.create_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_turnover_rate.amender
     *
     * @return the value of stock_turnover_rate.amender
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getAmender() {
        return amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_turnover_rate.amender
     *
     * @param amender the value for stock_turnover_rate.amender
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setAmender(Integer amender) {
        this.amender = amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_turnover_rate.amend_time
     *
     * @return the value of stock_turnover_rate.amend_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Date getAmendTime() {
        return amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_turnover_rate.amend_time
     *
     * @param amendTime the value for stock_turnover_rate.amend_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setAmendTime(Date amendTime) {
        this.amendTime = amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_turnover_rate.access_group
     *
     * @return the value of stock_turnover_rate.access_group
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getAccessGroup() {
        return accessGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_turnover_rate.access_group
     *
     * @param accessGroup the value for stock_turnover_rate.access_group
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setAccessGroup(Integer accessGroup) {
        this.accessGroup = accessGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_turnover_rate
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StockTurnoverRate other = (StockTurnoverRate) that;
        return (this.getStockTernoverRateId() == null ? other.getStockTernoverRateId() == null : this.getStockTernoverRateId().equals(other.getStockTernoverRateId()))
            && (this.getStockId() == null ? other.getStockId() == null : this.getStockId().equals(other.getStockId()))
            && (this.getTurnoverRate() == null ? other.getTurnoverRate() == null : this.getTurnoverRate().equals(other.getTurnoverRate()))
            && (this.getTurnoverDate() == null ? other.getTurnoverDate() == null : this.getTurnoverDate().equals(other.getTurnoverDate()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getAmender() == null ? other.getAmender() == null : this.getAmender().equals(other.getAmender()))
            && (this.getAmendTime() == null ? other.getAmendTime() == null : this.getAmendTime().equals(other.getAmendTime()))
            && (this.getAccessGroup() == null ? other.getAccessGroup() == null : this.getAccessGroup().equals(other.getAccessGroup()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_turnover_rate
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStockTernoverRateId() == null) ? 0 : getStockTernoverRateId().hashCode());
        result = prime * result + ((getStockId() == null) ? 0 : getStockId().hashCode());
        result = prime * result + ((getTurnoverRate() == null) ? 0 : getTurnoverRate().hashCode());
        result = prime * result + ((getTurnoverDate() == null) ? 0 : getTurnoverDate().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getAmender() == null) ? 0 : getAmender().hashCode());
        result = prime * result + ((getAmendTime() == null) ? 0 : getAmendTime().hashCode());
        result = prime * result + ((getAccessGroup() == null) ? 0 : getAccessGroup().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_turnover_rate
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", stockTernoverRateId=").append(stockTernoverRateId);
        sb.append(", stockId=").append(stockId);
        sb.append(", turnoverRate=").append(turnoverRate);
        sb.append(", turnoverDate=").append(turnoverDate);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", amender=").append(amender);
        sb.append(", amendTime=").append(amendTime);
        sb.append(", accessGroup=").append(accessGroup);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}