package com.stock.dao.model.stock;

import java.io.Serializable;
import java.util.Date;

public class StockTradeNum implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_num.stock_trade_num_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer stockTradeNumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_num.stock_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_num.stock_trade_num
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer stockTradeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_num.stock_trade_date
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Date stockTradeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_num.creator
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_num.create_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_num.amender
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer amender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_num.amend_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Date amendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_num.access_group
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private Integer accessGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_trade_num
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_num.stock_trade_num_id
     *
     * @return the value of stock_trade_num.stock_trade_num_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getStockTradeNumId() {
        return stockTradeNumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_num.stock_trade_num_id
     *
     * @param stockTradeNumId the value for stock_trade_num.stock_trade_num_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setStockTradeNumId(Integer stockTradeNumId) {
        this.stockTradeNumId = stockTradeNumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_num.stock_id
     *
     * @return the value of stock_trade_num.stock_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_num.stock_id
     *
     * @param stockId the value for stock_trade_num.stock_id
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_num.stock_trade_num
     *
     * @return the value of stock_trade_num.stock_trade_num
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getStockTradeNum() {
        return stockTradeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_num.stock_trade_num
     *
     * @param stockTradeNum the value for stock_trade_num.stock_trade_num
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setStockTradeNum(Integer stockTradeNum) {
        this.stockTradeNum = stockTradeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_num.stock_trade_date
     *
     * @return the value of stock_trade_num.stock_trade_date
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Date getStockTradeDate() {
        return stockTradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_num.stock_trade_date
     *
     * @param stockTradeDate the value for stock_trade_num.stock_trade_date
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setStockTradeDate(Date stockTradeDate) {
        this.stockTradeDate = stockTradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_num.creator
     *
     * @return the value of stock_trade_num.creator
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_num.creator
     *
     * @param creator the value for stock_trade_num.creator
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_num.create_time
     *
     * @return the value of stock_trade_num.create_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_num.create_time
     *
     * @param createTime the value for stock_trade_num.create_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_num.amender
     *
     * @return the value of stock_trade_num.amender
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getAmender() {
        return amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_num.amender
     *
     * @param amender the value for stock_trade_num.amender
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setAmender(Integer amender) {
        this.amender = amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_num.amend_time
     *
     * @return the value of stock_trade_num.amend_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Date getAmendTime() {
        return amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_num.amend_time
     *
     * @param amendTime the value for stock_trade_num.amend_time
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setAmendTime(Date amendTime) {
        this.amendTime = amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_num.access_group
     *
     * @return the value of stock_trade_num.access_group
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public Integer getAccessGroup() {
        return accessGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_num.access_group
     *
     * @param accessGroup the value for stock_trade_num.access_group
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    public void setAccessGroup(Integer accessGroup) {
        this.accessGroup = accessGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trade_num
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StockTradeNum other = (StockTradeNum) that;
        return (this.getStockTradeNumId() == null ? other.getStockTradeNumId() == null : this.getStockTradeNumId().equals(other.getStockTradeNumId()))
            && (this.getStockId() == null ? other.getStockId() == null : this.getStockId().equals(other.getStockId()))
            && (this.getStockTradeNum() == null ? other.getStockTradeNum() == null : this.getStockTradeNum().equals(other.getStockTradeNum()))
            && (this.getStockTradeDate() == null ? other.getStockTradeDate() == null : this.getStockTradeDate().equals(other.getStockTradeDate()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getAmender() == null ? other.getAmender() == null : this.getAmender().equals(other.getAmender()))
            && (this.getAmendTime() == null ? other.getAmendTime() == null : this.getAmendTime().equals(other.getAmendTime()))
            && (this.getAccessGroup() == null ? other.getAccessGroup() == null : this.getAccessGroup().equals(other.getAccessGroup()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trade_num
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStockTradeNumId() == null) ? 0 : getStockTradeNumId().hashCode());
        result = prime * result + ((getStockId() == null) ? 0 : getStockId().hashCode());
        result = prime * result + ((getStockTradeNum() == null) ? 0 : getStockTradeNum().hashCode());
        result = prime * result + ((getStockTradeDate() == null) ? 0 : getStockTradeDate().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getAmender() == null) ? 0 : getAmender().hashCode());
        result = prime * result + ((getAmendTime() == null) ? 0 : getAmendTime().hashCode());
        result = prime * result + ((getAccessGroup() == null) ? 0 : getAccessGroup().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trade_num
     *
     * @mbggenerated Thu Nov 01 14:24:56 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", stockTradeNumId=").append(stockTradeNumId);
        sb.append(", stockId=").append(stockId);
        sb.append(", stockTradeNum=").append(stockTradeNum);
        sb.append(", stockTradeDate=").append(stockTradeDate);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", amender=").append(amender);
        sb.append(", amendTime=").append(amendTime);
        sb.append(", accessGroup=").append(accessGroup);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}