package com.stock.dao.model.stock;

import java.io.Serializable;
import java.util.Date;

public class StockTradePrice implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_price.stock_trade_price_id
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    private Integer stockTradePriceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_price.stock_id
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    private Integer stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_price.trade_price
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    private Double tradePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_price.trade_date
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    private Date tradeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_price.creator
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_price.create_time
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_price.amender
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    private Integer amender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_price.amend_time
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    private Date amendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_trade_price.access_group
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    private Integer accessGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_trade_price
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_price.stock_trade_price_id
     *
     * @return the value of stock_trade_price.stock_trade_price_id
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public Integer getStockTradePriceId() {
        return stockTradePriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_price.stock_trade_price_id
     *
     * @param stockTradePriceId the value for stock_trade_price.stock_trade_price_id
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public void setStockTradePriceId(Integer stockTradePriceId) {
        this.stockTradePriceId = stockTradePriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_price.stock_id
     *
     * @return the value of stock_trade_price.stock_id
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_price.stock_id
     *
     * @param stockId the value for stock_trade_price.stock_id
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_price.trade_price
     *
     * @return the value of stock_trade_price.trade_price
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public Double getTradePrice() {
        return tradePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_price.trade_price
     *
     * @param tradePrice the value for stock_trade_price.trade_price
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public void setTradePrice(Double tradePrice) {
        this.tradePrice = tradePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_price.trade_date
     *
     * @return the value of stock_trade_price.trade_date
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public Date getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_price.trade_date
     *
     * @param tradeDate the value for stock_trade_price.trade_date
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public void setTradeDate(Date tradeDate) {
        this.tradeDate = tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_price.creator
     *
     * @return the value of stock_trade_price.creator
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_price.creator
     *
     * @param creator the value for stock_trade_price.creator
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_price.create_time
     *
     * @return the value of stock_trade_price.create_time
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_price.create_time
     *
     * @param createTime the value for stock_trade_price.create_time
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_price.amender
     *
     * @return the value of stock_trade_price.amender
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public Integer getAmender() {
        return amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_price.amender
     *
     * @param amender the value for stock_trade_price.amender
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public void setAmender(Integer amender) {
        this.amender = amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_price.amend_time
     *
     * @return the value of stock_trade_price.amend_time
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public Date getAmendTime() {
        return amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_price.amend_time
     *
     * @param amendTime the value for stock_trade_price.amend_time
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public void setAmendTime(Date amendTime) {
        this.amendTime = amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_trade_price.access_group
     *
     * @return the value of stock_trade_price.access_group
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public Integer getAccessGroup() {
        return accessGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_trade_price.access_group
     *
     * @param accessGroup the value for stock_trade_price.access_group
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    public void setAccessGroup(Integer accessGroup) {
        this.accessGroup = accessGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trade_price
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StockTradePrice other = (StockTradePrice) that;
        return (this.getStockTradePriceId() == null ? other.getStockTradePriceId() == null : this.getStockTradePriceId().equals(other.getStockTradePriceId()))
            && (this.getStockId() == null ? other.getStockId() == null : this.getStockId().equals(other.getStockId()))
            && (this.getTradePrice() == null ? other.getTradePrice() == null : this.getTradePrice().equals(other.getTradePrice()))
            && (this.getTradeDate() == null ? other.getTradeDate() == null : this.getTradeDate().equals(other.getTradeDate()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getAmender() == null ? other.getAmender() == null : this.getAmender().equals(other.getAmender()))
            && (this.getAmendTime() == null ? other.getAmendTime() == null : this.getAmendTime().equals(other.getAmendTime()))
            && (this.getAccessGroup() == null ? other.getAccessGroup() == null : this.getAccessGroup().equals(other.getAccessGroup()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trade_price
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStockTradePriceId() == null) ? 0 : getStockTradePriceId().hashCode());
        result = prime * result + ((getStockId() == null) ? 0 : getStockId().hashCode());
        result = prime * result + ((getTradePrice() == null) ? 0 : getTradePrice().hashCode());
        result = prime * result + ((getTradeDate() == null) ? 0 : getTradeDate().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getAmender() == null) ? 0 : getAmender().hashCode());
        result = prime * result + ((getAmendTime() == null) ? 0 : getAmendTime().hashCode());
        result = prime * result + ((getAccessGroup() == null) ? 0 : getAccessGroup().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_trade_price
     *
     * @mbggenerated Tue Oct 30 10:58:12 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", stockTradePriceId=").append(stockTradePriceId);
        sb.append(", stockId=").append(stockId);
        sb.append(", tradePrice=").append(tradePrice);
        sb.append(", tradeDate=").append(tradeDate);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", amender=").append(amender);
        sb.append(", amendTime=").append(amendTime);
        sb.append(", accessGroup=").append(accessGroup);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}